### ISSUE TITLE
after training, sample result is random noise 

### ISSUE THREAD

**Issue by jnkr36** [NUAAerJC/classifier-free-diffusion-guidance#1]
I tried twice, set epoch=20 and 300, after traing, the sampled result are all random noise.
I didn't change any other parameter, is there anything wrong with the training process?
![image](https://user-images.githubusercontent.com/36756751/216954033-2b7e0383-94f8-48e1-8122-76f546a72997.png)

**Comment by jcwang-gh** [comment]
I will fix this issue in the next one or two days. There is nothing wrong during the training process, the reason is that some parameters used for sampling in the file diffusion.py were wrongly set.

**Comment by jcwang-gh** [comment]
Sorry for the inconvenience.

**Comment by jcwang-gh** [comment]
I just updated the file diffusion.py a few minutes before, now the issue should be solved. You don't need to retrain your model. @jnkr36

**Comment by NUAAerJC** [comment]
I just updated the file diffusion.py a few minutes before, now the issue should be solved. You don't need to retrain your model.
