### ISSUE TITLE
FID and IS evaluation indicators

### ISSUE THREAD

**Issue by Think520change** [NUAAerJC/classifier-free-diffusion-guidance#11]
Hello, thank the author for the work contribution of reproducing the code. Now I am looking at the code process, and I want to complete the numerical calculation of the FID and IS evaluation indicators in the paper and print them to the terminal. Have you considered how to calculate these two indicators? Thank you for your reply.

**Comment by jcwang-gh** [comment]
the code used for FID calculation can be found in https://github.com/openai/guided-diffusion and you need to run it in a tensorflow docker container.

**Comment by Think520change** [comment]
Thank you very much for your answer and reply.

**Comment by jcwang-gh** [comment]
no problem. If you have any other questions, feel free to ask.
