### ISSUE TITLE
Unable to receive conditional results

### ISSUE THREAD

**Issue by AzusaXuan** [NUAAerJC/classifier-free-diffusion-guidance#2]
Hi! I'm excited to find such excellent work, but unfortunately, I failed to obtain conditional images following your instruction. I have run the train.py for 1000 epochs, but I found output like img1 which seems random after I set --label range 
![sample_999_labelrange_w11 0_T1000_pict](https://user-images.githubusercontent.com/91823131/220814913-d816c2fd-81cc-4d67-b65f-eddb326e1ee5.png)
Therefore, I modified part of the code in sample.py shown in img2 so that I can output single-kind pictures ranging from 0 to 9
![LU~9NJDM8 $MI4GL8RM% C](https://user-images.githubusercontent.com/91823131/220815685-16ae1e2f-2265-4c84-bc9f-94e156adee1f.png)

and ran orders like " python sample.py --label 0 --device cuda:1 --epc 999 --w 5.0 --T 1000", but still got random images shown in img3.
![sample_999_label0_w5 0_T1000_pict](https://user-images.githubusercontent.com/91823131/220815761-f354068e-ad59-4d50-8418-f7ea689c9b17.png)

I wonder if you could help out with this problem. Thanks a lot!

**Comment by jcwang-gh** [comment]
I will solve this issue in a week or two.

**Comment by AzusaXuan** [comment]
> I will solve this issue in a week or two.

thanks for your reply, looking forward to your solution!

**Comment by jcwang-gh** [comment]
I have updated a lot of files, but to solve the issue you just need to download only one file : diffusion.py and replace all the `{'cemb':cemb}` in train.py and sample.py with `cemb=cemb`. **You do not need to retrain your model.** I guess there was something wrong when passing parameters from `diffusion` to `unet` previously but I do not know the specific reason. If there are any other problems, please tell me.
